/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author JALEXISRDV
 */
public class PanelPort extends javax.swing.JPanel {

    /**
     * Creates new form PanelPort
     */
    public PanelPort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorth = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        panelLabel = new javax.swing.JPanel();
        lb0 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        panelCheckBox = new javax.swing.JPanel();
        cbx0 = new javax.swing.JCheckBox();
        cbx1 = new javax.swing.JCheckBox();
        cbx2 = new javax.swing.JCheckBox();
        cbx3 = new javax.swing.JCheckBox();
        cbx4 = new javax.swing.JCheckBox();
        cbx5 = new javax.swing.JCheckBox();
        cbx6 = new javax.swing.JCheckBox();
        cbx7 = new javax.swing.JCheckBox();
        panelSouth = new javax.swing.JPanel();
        btnPrenderTodos = new javax.swing.JButton();
        btnApagarTodos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20));
        panelNorth.setOpaque(false);
        panelNorth.setLayout(new java.awt.GridLayout(1, 0));

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Lenguajes de Interfaz");
        panelNorth.add(lbTitle);

        add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setOpaque(false);
        panelCenter.setLayout(new java.awt.GridLayout(2, 0));

        panelLabel.setOpaque(false);
        panelLabel.setLayout(new java.awt.GridLayout(1, 8, 10, 0));

        lb0.setBackground(new java.awt.Color(255, 143, 50));
        lb0.setForeground(new java.awt.Color(255, 255, 255));
        lb0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb0.setText("D0");
        lb0.setOpaque(true);
        panelLabel.add(lb0);

        lb1.setBackground(new java.awt.Color(255, 143, 50));
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("D1");
        lb1.setOpaque(true);
        panelLabel.add(lb1);

        lb2.setBackground(new java.awt.Color(255, 143, 50));
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("D2");
        lb2.setOpaque(true);
        panelLabel.add(lb2);

        lb3.setBackground(new java.awt.Color(255, 143, 50));
        lb3.setForeground(new java.awt.Color(255, 255, 255));
        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("D3");
        lb3.setOpaque(true);
        panelLabel.add(lb3);

        lb4.setBackground(new java.awt.Color(255, 143, 50));
        lb4.setForeground(new java.awt.Color(255, 255, 255));
        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb4.setText("D4");
        lb4.setOpaque(true);
        panelLabel.add(lb4);

        lb5.setBackground(new java.awt.Color(255, 143, 50));
        lb5.setForeground(new java.awt.Color(255, 255, 255));
        lb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb5.setText("D5");
        lb5.setOpaque(true);
        panelLabel.add(lb5);

        lb6.setBackground(new java.awt.Color(255, 143, 50));
        lb6.setForeground(new java.awt.Color(255, 255, 255));
        lb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb6.setText("D6");
        lb6.setOpaque(true);
        panelLabel.add(lb6);

        lb7.setBackground(new java.awt.Color(255, 143, 50));
        lb7.setForeground(new java.awt.Color(255, 255, 255));
        lb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb7.setText("D7");
        lb7.setOpaque(true);
        panelLabel.add(lb7);

        panelCenter.add(panelLabel);

        panelCheckBox.setOpaque(false);
        panelCheckBox.setLayout(new java.awt.GridLayout(1, 8, 10, 0));

        cbx0.setForeground(new java.awt.Color(255, 255, 255));
        cbx0.setText("D0");
        cbx0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx0.setOpaque(false);
        panelCheckBox.add(cbx0);

        cbx1.setForeground(new java.awt.Color(255, 255, 255));
        cbx1.setText("D1");
        cbx1.setOpaque(false);
        panelCheckBox.add(cbx1);

        cbx2.setForeground(new java.awt.Color(255, 255, 255));
        cbx2.setText("D2");
        cbx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx2.setOpaque(false);
        panelCheckBox.add(cbx2);

        cbx3.setForeground(new java.awt.Color(255, 255, 255));
        cbx3.setText("D3");
        cbx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx3.setOpaque(false);
        panelCheckBox.add(cbx3);

        cbx4.setForeground(new java.awt.Color(255, 255, 255));
        cbx4.setText("D4");
        cbx4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx4.setOpaque(false);
        panelCheckBox.add(cbx4);

        cbx5.setForeground(new java.awt.Color(255, 255, 255));
        cbx5.setText("D5");
        cbx5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx5.setOpaque(false);
        panelCheckBox.add(cbx5);

        cbx6.setForeground(new java.awt.Color(255, 255, 255));
        cbx6.setText("D6");
        cbx6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx6.setOpaque(false);
        panelCheckBox.add(cbx6);

        cbx7.setForeground(new java.awt.Color(255, 255, 255));
        cbx7.setText("D7");
        cbx7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbx7.setOpaque(false);
        panelCheckBox.add(cbx7);

        panelCenter.add(panelCheckBox);

        add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setOpaque(false);
        panelSouth.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnPrenderTodos.setBackground(new java.awt.Color(255, 255, 255));
        btnPrenderTodos.setText("Prender Todos");
        btnPrenderTodos.setName("btnPrender"); // NOI18N
        panelSouth.add(btnPrenderTodos);

        btnApagarTodos.setBackground(new java.awt.Color(255, 255, 255));
        btnApagarTodos.setText("Apagar Todos");
        btnApagarTodos.setName("btnApagar"); // NOI18N
        panelSouth.add(btnApagarTodos);

        add(panelSouth, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarTodos;
    private javax.swing.JButton btnPrenderTodos;
    private javax.swing.JCheckBox cbx0;
    private javax.swing.JCheckBox cbx1;
    private javax.swing.JCheckBox cbx2;
    private javax.swing.JCheckBox cbx3;
    private javax.swing.JCheckBox cbx4;
    private javax.swing.JCheckBox cbx5;
    private javax.swing.JCheckBox cbx6;
    private javax.swing.JCheckBox cbx7;
    private javax.swing.JLabel lb0;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelCheckBox;
    private javax.swing.JPanel panelLabel;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSouth;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel[] getAllLbs() {
        javax.swing.JLabel[] lbs = {lb0, lb1, lb2, lb3, lb4, lb5, lb6, lb7};
        return lbs; 
    }
    
    public javax.swing.JCheckBox[] getAllCbxs() {
        javax.swing.JCheckBox[] cbxs = {cbx0, cbx1, cbx2, cbx3, cbx4, cbx5, cbx6, cbx7};
        return cbxs; 
    }
    
    /**
     * @return the btnApagarTodos
     */
    public javax.swing.JButton getBtnApagarTodos() {
        return btnApagarTodos;
    }

    /**
     * @return the btnPrenderTodos
     */
    public javax.swing.JButton getBtnPrenderTodos() {
        return btnPrenderTodos;
    }

    /**
     * @return the cbx0
     */
    public javax.swing.JCheckBox getCbx0() {
        return cbx0;
    }

    /**
     * @return the cbx1
     */
    public javax.swing.JCheckBox getCbx1() {
        return cbx1;
    }

    /**
     * @return the cbx2
     */
    public javax.swing.JCheckBox getCbx2() {
        return cbx2;
    }

    /**
     * @return the cbx3
     */
    public javax.swing.JCheckBox getCbx3() {
        return cbx3;
    }

    /**
     * @return the cbx4
     */
    public javax.swing.JCheckBox getCbx4() {
        return cbx4;
    }

    /**
     * @return the cbx5
     */
    public javax.swing.JCheckBox getCbx5() {
        return cbx5;
    }

    /**
     * @return the cbx6
     */
    public javax.swing.JCheckBox getCbx6() {
        return cbx6;
    }

    /**
     * @return the cbx7
     */
    public javax.swing.JCheckBox getCbx7() {
        return cbx7;
    }

    /**
     * @return the lb0
     */
    public javax.swing.JLabel getLb0() {
        return lb0;
    }

    /**
     * @return the lb1
     */
    public javax.swing.JLabel getLb1() {
        return lb1;
    }

    /**
     * @return the lb2
     */
    public javax.swing.JLabel getLb2() {
        return lb2;
    }

    /**
     * @return the lb3
     */
    public javax.swing.JLabel getLb3() {
        return lb3;
    }

    /**
     * @return the lb4
     */
    public javax.swing.JLabel getLb4() {
        return lb4;
    }

    /**
     * @return the lb5
     */
    public javax.swing.JLabel getLb5() {
        return lb5;
    }

    /**
     * @return the lb6
     */
    public javax.swing.JLabel getLb6() {
        return lb6;
    }

    /**
     * @return the lb7
     */
    public javax.swing.JLabel getLb7() {
        return lb7;
    }

    /**
     * @return the lbTitle
     */
    public javax.swing.JLabel getLbTitle() {
        return lbTitle;
    }

    /**
     * @return the panelCenter
     */
    public javax.swing.JPanel getPanelCenter() {
        return panelCenter;
    }

    /**
     * @return the panelCheckBox
     */
    public javax.swing.JPanel getPanelCheckBox() {
        return panelCheckBox;
    }

    /**
     * @return the panelLabel
     */
    public javax.swing.JPanel getPanelLabel() {
        return panelLabel;
    }

    /**
     * @return the panelNorth
     */
    public javax.swing.JPanel getPanelNorth() {
        return panelNorth;
    }

    /**
     * @return the panelSouth
     */
    public javax.swing.JPanel getPanelSouth() {
        return panelSouth;
    }
}
